# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: âœ… Check project in different Node versions
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  check-node-build:
    name: ğŸ§© Build and test code
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20, 22 ]
    steps:
    - name: ğŸ”€ Checkout code from repository
      uses: actions/checkout@v6.0.1
    - name: ğŸ› ï¸ Setup Node version ${{ matrix.node-version }}
      uses: actions/setup-node@v6.1.0
      with:
        node-version: ${{ matrix.node-version }}
    - name: ğŸ“¦ Install dependencies
      run: npm install
    - name: ğŸ—ï¸ Build project
      run: npm run build --if-present
    - name: ğŸ§ª Test code
      run: npm test --if-present
